package com.zx80live.gofp.bootstrap

import java.io.{BufferedWriter, File, FileWriter}

object IoUtils {
  //TODO move to the config
  val root = "/home/work/gofp/fp/"

  def toFile(filename: String,
             dir: String = "",
             pack: String = "fp",
             imports: Seq[String] = Nil,
             content: Seq[String] = Nil): Unit = {
    new File(root + "/" + dir).mkdirs()
    val file = new File(root + "/" + dir + "/" + filename)
    val writer = new BufferedWriter(new FileWriter(file))

    try {
      writer.write(
        s"""// $filename
           |// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap
           |
           |package $pack
           |
           |${imports.map { i => if(i.startsWith(".")) "import " + i else { "import \"" + i + "\""} }.mkString("", "\n", "")}""".stripMargin
      )
      content foreach writer.write
    } finally {
      writer.flush()
      writer.close()
    }
  }
}
