package com.zx80live.gofp.bootstrap.refactored

import java.io.{BufferedWriter, File, FileWriter}

object IoUtils {
  //TODO move to the config
  val root = "/home/work/gofp/fp/"

  def toFile(filename: String,
             pack: String = "fp",
             imports: Seq[String] = Nil,
             content: Seq[String] = Nil): Unit = {
    val writer = new BufferedWriter(new FileWriter(new File(root + "/" + filename)))

    try {
      writer.write(
        s"""// $filename
           |// DO NOT EDIT THIS FILE WAS GENERATED AUTOMATICALLY BY https://github.com/zx80live/gofp-bootstrap
           |
           |package $pack
           |
           |${imports.map(i => "import \"" + i + "\"").mkString("", "\n", "")}""".stripMargin
      )
      content foreach writer.write
    } finally {
      writer.close()
    }
  }
}
